name: Deploy dosh-reactjs to Hetzner

on:
  push:
    branches: [ main ]

jobs:
  BPD:
    runs-on: ubuntu-24.04
  
    env:
      DOCKER_IMAGE: "${{ github.ref_name }}:${{ github.sha }}"
      DOCKER_IMAGE_TAR: "${{ github.ref_name }}.tar"

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Checkout repository
      uses:  actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build webapp
      run: |
        docker build . -t webapp-${{ env.DOCKER_IMAGE }} --platform linux/amd64

    - name: Save Docker Image webapp
      run: |
        docker save --output webapp-${{ env.DOCKER_IMAGE_TAR }} webapp-${{ env.DOCKER_IMAGE }} 
        chmod 664 webapp-${{ env.DOCKER_IMAGE_TAR }}

    - name: Copy Docker image to host
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "webapp-${{ env.DOCKER_IMAGE_TAR }}"
        target: "webapp-${{ env.DOCKER_IMAGE_TAR }}"
        
    - name: Load Docker Image
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: | 
          docker load -i webapp-${{ env.DOCKER_IMAGE_TAR }}/webapp-${{ env.DOCKER_IMAGE_TAR }}
    
    - name: Update Docker Compose 
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: | 
          yq w -i dosh/docker-compose.yml 'services.webapp-${{ github.ref_name }}.image' 'webapp-${{ github.ref_name }}:${{ github.sha }}'
    
    - name: Recreate images
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: | 
          cd dosh
          docker rollout webapp-${{ github.ref_name }}
          
    - name: Clean up old images
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: | 
          docker image prune -a -f
