
name: Deploy dosh-reactjs to Hetzner

on:
  push:
    branches: [ main ]

jobs:
  BPD:
    runs-on: ubuntu-24.04
  
    env:
      DOCKER_IMAGE: "${{ github.ref_name }}:${{ github.sha }}"
      DOCKER_IMAGE_TAR: "${{ github.ref_name }}.tar"

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Checkout repository
      uses:  actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # - name: Build backend
    #   run: |
    #     cd backend
    #     docker build . -t backend-${{ env.DOCKER_IMAGE }} --platform linux/amd64

    - name: Build frontend
      run: |
        docker build . -t frontend-${{ env.DOCKER_IMAGE }} --platform linux/amd64

    # - name: Save Docker Image backend
    #   run: |
    #     docker save --output backend-${{ env.DOCKER_IMAGE_TAR }} backend-${{ env.DOCKER_IMAGE }} 
    #     chmod 664 backend-${{ env.DOCKER_IMAGE_TAR }}

    - name: Save Docker Image frontend
      run: |
        docker save --output frontend-${{ env.DOCKER_IMAGE_TAR }} frontend-${{ env.DOCKER_IMAGE }} 
        chmod 664 frontend-${{ env.DOCKER_IMAGE_TAR }}

    # - name: Copy Docker image(backend) to host
    #   uses: appleboy/scp-action@v0.1.7
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USER }}
    #     key: ${{ secrets.KEY }}
    #     port: ${{ secrets.PORT }}
    #     source: "backend-${{ env.DOCKER_IMAGE_TAR }}"
    #     target: "backend-${{ env.DOCKER_IMAGE_TAR }}"

    - name: Copy Docker image to host
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "frontend-${{ env.DOCKER_IMAGE_TAR }}"
        target: "frontend-${{ env.DOCKER_IMAGE_TAR }}"
        
    - name: Load Docker Image
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: | 
          docker load -i frontend-${{ env.DOCKER_IMAGE_TAR }}/frontend-${{ env.DOCKER_IMAGE_TAR }}
    
    - name: Update Docker Compose 
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: | 
          yq w -i dosh/docker-compose.yml 'services.frontend-${{ github.ref_name }}.image' 'frontend-${{ github.ref_name }}:${{ github.sha }}'
    
    - name: Recreate images
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: | 
          cd dosh
          docker rollout frontend-${{ github.ref_name }}
          
    - name: Clean up old images
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: | 
          docker image prune -a -f

    
        


          

